### PR TITLE
Add Home page and restyle the navigation.

### PR DESCRIPTION
**Pull request by kapoorlakshya**

### CODE REVIEW

**Comment by kapoorlakshya** [comment]
**Short version**: It is not specific to Users routes. I removed it from the global level.

**Long version**: So having the filter in the ApplicationController enabled it on all other controllers. I couldn't figure out how to add other controllers as exceptions to it. The Rails doc only mentions adding Controller methods as exceptions.

That made me think that maybe the best practice is to add the filter to specific controllers instead of having it at the global level. Since Users was the only controller available, I updated that. Now that we are merging in Schedules and Shifts soon, we can add the filter to them as well.

Do you know of a way to excluding controllers from the filter?

**Comment by maxdobeck** [comment]
So for example which controllers would we want to exclude?

But to accomplish that it should be 'skip_before_filter : authenticate_user'. More examples on the rails action controller doc.

**Comment by kapoorlakshya** [comment]
`skip_before_filter : authenticate_user`

Ah, that is what I need. Oaky, I will add the authentication filter back to the global level and skip it on `HomeController`.

**Comment by maxdobeck** [comment]
Excellent!  Sorry I didn't find the up to date API. Good work.

**Comment by kapoorlakshya** [comment]
Oh, no problem. You pointed me in the right direction ☺️

**Comment by maxdobeck** [comment]
Did I merge this pull to request?

**Comment by maxdobeck** [comment]
I mean, did I merge this pull request too soon?

**Comment by kapoorlakshya** [comment]
It was ready to be merged. I'm going to hold off on styling further until we get the core features in.

**Pull request merged**
